# Generated by Django 4.2.4 on 2023-08-23 14:25

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="GH", max_length=2, verbose_name="Country"
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("region", models.CharField(max_length=50)),
                (
                    "city",
                    models.CharField(
                        default="Accra", max_length=180, verbose_name="City"
                    ),
                ),
                ("digital_address", models.CharField(max_length=15)),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="GH"
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        default="say something about yourself", verbose_name="About me"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        upload_to=apps.profiles.models.upload_profile_photo,
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("Male", "Male"),
                            ("female", "female"),
                            ("Female", "Female"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "neck",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Around neck",
                    ),
                ),
                (
                    "bust",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Bust area",
                    ),
                ),
                (
                    "arm_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Arm length short",
                    ),
                ),
                (
                    "long_sleeve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Arm length long",
                    ),
                ),
                (
                    "bicep",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Bicep",
                    ),
                ),
                (
                    "wrist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Wrist",
                    ),
                ),
                (
                    "torso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Torso length",
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Waist",
                    ),
                ),
                (
                    "hips",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="hips",
                    ),
                ),
                (
                    "waist_to_above_knee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Skirt/ Shorts length",
                    ),
                ),
                (
                    "waist_to_below_knee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Trouser length",
                    ),
                ),
                (
                    "calf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=2,
                        null=True,
                        verbose_name="Calf",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
